quarkus.http.port=${KNALS_PORT:8080}

knals.config.dir=${KNALS_CONFIG_DIR:${user.home}/.config/knals}

quarkus.smallrye-openapi.info-title=knals
quarkus.smallrye-openapi.info-version=${quarkus.application.version:0.1.0}
quarkus.smallrye-openapi.store-schema-directory=target/openapi

%dev.quarkus.kubernetes-client.devservices.enabled=false
